CREATE TABLE Novatek.dbo.CLIENT(
ID_CLIENT INT NOT NULL,
CLIENT_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (ID_CLIENT));

CREATE TABLE Novatek.dbo.PRODUCT(
ID_PRODUCT INT NOT NULL,
PRODUCT_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY(ID_PRODUCT));

CREATE TABLE Novatek.dbo.DOCUMENT(
ID_DOCUMENT INT NOT NULL,
ID_CLIENT INT NOT NULL,
DATEDOK DATETIME NOT NULL,
TYPE_DOK BIT NOT NULL,
PRIMARY KEY(ID_DOCUMENT),
FOREIGN KEY(ID_CLIENT) REFERENCES Novatek.dbo.CLIENT);

CREATE TABLE Novatek.dbo.POSITION(
ID_POSITION INT NOT NULL,
ID_DOCUMENT INT NOT NULL,
VOLUME INT NOT NULL,
ID_PRODUCT INT NOT NULL,
PRIMARY KEY(ID_POSITION),
FOREIGN KEY(ID_DOCUMENT) REFERENCES Novatek.dbo.DOCUMENT,
FOREIGN KEY(ID_PRODUCT) REFERENCES Novatek.dbo.PRODUCT);



