USE Novatek;

SELECT P.ID_PRODUCT, PR.PRODUCT_NAME, 
SUM(CASE WHEN TYPE_DOK = 0 THEN P.VOLUME ELSE 0 END) AS SUMAZAKUPU,
SUM(CASE WHEN TYPE_DOK = 1 THEN P.VOLUME ELSE 0 END) AS SUMASPRZEDAZY
FROM POSITION AS P
JOIN DOCUMENT AS D ON P.ID_DOCUMENT = D.ID_DOCUMENT
JOIN PRODUCT AS PR ON P.ID_PRODUCT = PR.ID_PRODUCT
WHERE YEAR(D.DATEDOK) = 2019
GROUP BY P.ID_PRODUCT, PR.PRODUCT_NAME
ORDER BY SUMAZAKUPU DESC, SUMASPRZEDAZY DESC