USE Novatek;

SELECT CLIENT_NAME, PRODUCT_NAME FROM (SELECT DISTINCT ID_PRODUCT, ID_CLIENT FROM POSITION AS P
JOIN DOCUMENT AS D ON P.ID_DOCUMENT = D.ID_DOCUMENT
WHERE TYPE_DOK = 1) AS T1
RIGHT JOIN (SELECT * FROM PRODUCT CROSS JOIN CLIENT) AS T2
ON T1.ID_CLIENT = T2.ID_CLIENT AND T1.ID_PRODUCT = T2.ID_PRODUCT
WHERE T1.ID_PRODUCT IS NULL AND T1.ID_CLIENT IS NULL