USE Novatek;

SELECT CLIENT_NAME FROM CLIENT AS C1 
LEFT JOIN (SELECT DISTINCT C.ID_CLIENT FROM DOCUMENT AS D
		   RIGHT JOIN CLIENT AS C ON D.ID_CLIENT = C.ID_CLIENT
		   WHERE (YEAR(D.DATEDOK) = 2019 OR D.DATEDOK IS NULL)
		   AND TYPE_DOK = 1) AS T1 ON C1.ID_CLIENT = T1.ID_CLIENT
WHERE T1.ID_CLIENT IS NULL;